### ISSUE TITLE
/site: fails to export some routes

### ISSUE THREAD

**Issue by mindrones** [nestauk/svizzle#338] opened 2021-07-14 14:21 UTC
```
   45.7 kB   compounds/time_region_value/muhbi/2012/index.html
   46.7 kB   compounds/time_region_value/muhbi/2013/index.html
   46.7 kB   compounds/time_region_value/muhbi/2014/index.html
   46.7 kB   compounds/time_region_value/muhbi/2015/index.html
   39.3 kB   compounds/time_region_value/aroda/2010/index.html
   38.8 kB   compounds/time_region_value/aroda/2011/index.html
   38.8 kB   compounds/time_region_value/aroda/2012/index.html
   39.9 kB   compounds/time_region_value/aroda/2013/index.html
   39.9 kB   compounds/time_region_value/aroda/2014/index.html
   3.79 kB   client/types-8035ae94.css
   3.73 kB   client/index-3776ea31.css
    144 kB   client/index.39dcfead.js
    186 kB   client/types.6beba065.js
   10.6 kB   client/regionSelection.4c62497e.js
   5.02 kB   (500) compounds/time_region_value/milow/2014/index.html
   5.02 kB   (500) compounds/time_region_value/fukag/2007/index.html
   5.02 kB   (500) compounds/time_region_value/fukag/2008/index.html
   5.02 kB   (500) compounds/time_region_value/fukag/2009/index.html
   5.02 kB   (500) compounds/time_region_value/acpuf/2008/index.html
   5.02 kB   (500) compounds/time_region_value/acpuf/2013/index.html
   5.02 kB   (500) compounds/time_region_value/acpuf/2014/index.html
   5.02 kB   (500) compounds/time_region_value/acpuf/2015/index.html
   5.02 kB   (500) compounds/time_region_value/acpuf/2016/index.html
   5.02 kB   (500) compounds/time_region_value/acpuf/2017/index.html
   5.02 kB   (500) compounds/time_region_value/jiduh/2013/index.html
   5.02 kB   (500) compounds/time_region_value/ulvef/2009/index.html
   5.02 kB   (500) compounds/time_region_value/uvoug/2017/index.html
   5.02 kB   (500) compounds/time_region_value/kojze/2006/index.html
   5.02 kB   (500) compounds/time_region_value/kojze/2007/index.html
   5.02 kB   (500) compounds/time_region_value/kojze/2008/index.html
   5.02 kB   (500) compounds/time_region_value/kojze/2009/index.html
   5.02 kB   (500) compounds/time_region_value/kojze/2016/index.html
   5.02 kB   (500) compounds/time_region_value/zehim/2015/index.html
   5.02 kB   (500) compounds/time_region_value/revbi/2006/index.html
   5.02 kB   (500) compounds/time_region_value/revbi/2007/index.html
   5.02 kB   (500) compounds/time_region_value/muhbi/2006/index.html
   5.02 kB   (500) compounds/time_region_value/muhbi/2016/index.html
   5.02 kB   (500) compounds/time_region_value/aroda/2007/index.html
   5.02 kB   (500) compounds/time_region_value/aroda/2008/index.html
   5.02 kB   (500) compounds/time_region_value/aroda/2009/index.html
   5.02 kB   (500) compounds/time_region_value/aroda/2015/index.html
```

**Comment by saabi** [comment] 2021-11-25 12:15
Couldn't reproduce. Closing.

The URLs causing the 500 error during export aren't in the range of included years for the IDs given in the issue.

At first I thought it might be a bug in the URL generation, but after verifying the code and finally exporting the doc site I found that there are no errors being reported locally.

I'm not sure what could have caused the error originally, but I failed to reproduce it here.

**Closed as completed** 2021-11-25 12:15 UTC
Labels: package:site
